services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - memcached
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=flashsale
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211

  mysql:
    image: mysql:8.0.40
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flashsale
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  memcached:
    image: memcached:1.6.37-alpine3.21
    restart: always
    ports:
      - "11211:11211"

volumes:
  mysql_data:
