# Health Check
GET http://localhost:3000/ HTTP/1.1

###

# Create a new product
# This request creates a new product with required details.
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Flashlight",
  "description": "High-intensity LED flashlight",
  "price": 29.99,
  "inventory": 100
}

###

# Get all products
# Retrieves the list of all products.
GET http://localhost:3000/products HTTP/1.1

###

# Get a product by ID
GET http://localhost:3000/products/5 HTTP/1.1

###

# Update a product
PUT http://localhost:3000/products/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Flashlight Updated",
  "description": "Updated description for LED flashlight",
  "price": 24.99,
  "inventory": 90
}

###

# Purchase a product
# (Decrements inventory by 1)
POST http://localhost:3000/products/1/purchase HTTP/1.1

###

# Increment product view count
# This endpoint increments the view counter for the product.
GET http://localhost:3000/products/5/views HTTP/1.1

###

# Delete a product
DELETE http://localhost:3000/products/4 HTTP/1.1

###

# Flush cache
# This admin endpoint cleasr all memcached data
GET http://localhost:3000/cache/flush HTTP/1.1
